### ISSUE TITLE
Start and stop actions

### ISSUE THREAD

**Issue by Mi-Py-1** [Mi-Py-1/TypeRacer-AI-Pair-Programming#3]
**Acceptance Criteria:**

- [x] The test begins by user action, such as clicking a start button
- [x] The test ends by user action, such as clicking a stop button
- [x] It is clear to the user how they can start and stop the test

**Tasks:**

- [x] Create a user action that triggers the start of the test
- [x] Create a user action that triggers the end of the test
- [x] Create clear actions the user needs to take to start and stop the test
