### ISSUE TITLE
Display best test results for each difficulty level

### ISSUE THREAD

**Issue by Mi-Py-1** [Mi-Py-1/TypeRacer-AI-Pair-Programming#9]
As a competitive user, I want my best results for each difficulty level to be displayed so that I can compare my progress.

**Acceptance Criteria:**

- [x] The best test result for each level is stored
- [x] The best test result for each level is displayed on the site

**Tasks:**

- [x] Create an area to display the best test results for each level of difficulty
- [x] The best test result for each level is stored and displayed to the user
